//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEditor
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Buy
    {
        public int Id_Year { get; set; }
        public double id { get; set; }
        public string BuyDate { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Discount2 { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> totoal { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> bank { get; set; }
        public Nullable<double> Pay { get; set; }
        public Nullable<double> id_book { get; set; }
        public Nullable<double> id_account { get; set; }
        public string Creattor { get; set; }
        public string editor { get; set; }
        public string CrateDate { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> area { get; set; }
    }
}
