//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEditor.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Company
    {
        public int SHS_ID { get; set; }
        public int ID { get; set; }
        public string name { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string @delegate { get; set; }
        public string tozih { get; set; }
    
        public virtual SalMaly SalMaly { get; set; }
    }
}
