//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEditor.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Agreement
    {
        public int SHS_ID { get; set; }
        public string name { get; set; }
        public int ID_Company { get; set; }
        public string tar { get; set; }
        public Nullable<double> mabkol { get; set; }
        public string sho { get; set; }
        public int ID { get; set; }
        public string tar1 { get; set; }
        public string tar2 { get; set; }
        public string tozih { get; set; }
        public Nullable<double> darn { get; set; }
        public Nullable<double> darq { get; set; }
        public Nullable<double> dare { get; set; }
        public Nullable<double> darb { get; set; }
        public string tozihn { get; set; }
        public string tozihq { get; set; }
        public string tozihe { get; set; }
        public string tozihb { get; set; }
        public Nullable<double> creditq { get; set; }
        public Nullable<double> credite { get; set; }
        public Nullable<double> creditb { get; set; }
        public Nullable<double> cod_hce { get; set; }
        public Nullable<double> cod_hme { get; set; }
        public Nullable<double> cod_hcb { get; set; }
        public Nullable<double> cod_hmb { get; set; }
    
        public virtual SalMaly SalMaly { get; set; }
    }
}
