//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEditor.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Setting
    {
        public int SHS_ID { get; set; }
        public string takh { get; set; }
        public string MsgADD { get; set; }
        public string MsgEdit { get; set; }
        public string MsgDel { get; set; }
        public string MsgAddFffo { get; set; }
        public string MsgAddMfo { get; set; }
        public Nullable<double> Discount { get; set; }
        public string TypeDiscount { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string LibKey { get; set; }
        public string Host_ { get; set; }
        public string MsgTavalod { get; set; }
        public string MsgEzdevaj { get; set; }
        public Nullable<double> PersonelDiscount { get; set; }
        public string MsgOmoomi { get; set; }
        public string MsgOmoomi2 { get; set; }
        public Nullable<int> facRound { get; set; }
        public int shs_id_FFO { get; set; }
        public string FacTozihTavalod { get; set; }
        public Nullable<double> DiscountTavalod { get; set; }
        public Nullable<double> DiscountKasian { get; set; }
        public string FactozihKasian { get; set; }
        public string FacTozihEzdevaj { get; set; }
        public Nullable<double> DiscountEzdevaj { get; set; }
        public string FacTozih { get; set; }
        public string FacTozihPersonelDiscount { get; set; }
        public string terminal_id { get; set; }
        public string merch_number { get; set; }
        public string terminalpass { get; set; }
        public string terminalDelpass { get; set; }
        public string SMSTYpe { get; set; }
        public string Msgffo_1 { get; set; }
        public string Msgffo_2 { get; set; }
        public string Msgffo_3 { get; set; }
        public string Msgffo_4 { get; set; }
        public string Msgffo_5 { get; set; }
        public string terminal_id2 { get; set; }
        public string terminalUser { get; set; }
        public string merch_number2 { get; set; }
        public string terminalpass2 { get; set; }
        public string terminalDelpass2 { get; set; }
        public string terminalUser2 { get; set; }
        public Nullable<double> kasian_cod_hc { get; set; }
        public Nullable<double> kasian_cod_hm_e { get; set; }
        public Nullable<double> kasian_cod_hm_b { get; set; }
        public Nullable<double> kasian_cod_hm_m { get; set; }
        public Nullable<double> kasian_cod_hm_m2 { get; set; }
    
        public virtual SalMaly SalMaly { get; set; }
    }
}
