//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEditor.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ffo
    {
        public int SHS_ID { get; set; }
        public string NOE_F { get; set; }
        public double COD { get; set; }
        public string TAR { get; set; }
        public Nullable<double> TAKH { get; set; }
        public Nullable<double> GH_NA { get; set; }
        public Nullable<double> COD_SA { get; set; }
        public Nullable<double> NAGHD { get; set; }
        public string TOZIH { get; set; }
        public string NOE_TAKH { get; set; }
        public Nullable<double> CHEK { get; set; }
        public Nullable<double> COD_HC { get; set; }
        public Nullable<double> COD_HM { get; set; }
        public Nullable<double> GH_FA { get; set; }
        public Nullable<double> GH_MAN { get; set; }
        public Nullable<double> HAZ { get; set; }
        public string SHOMS { get; set; }
        public string TAR_S { get; set; }
        public string TAR_V { get; set; }
        public string VAZ { get; set; }
        public string PAR_HAZ { get; set; }
        public Nullable<double> COD_HC_VI { get; set; }
        public Nullable<double> COD_HM_VI { get; set; }
        public Nullable<double> MAB_VI { get; set; }
        public Nullable<double> JAM_TED { get; set; }
        public Nullable<double> JAM_ZAR { get; set; }
        public Nullable<double> TAKH_TED { get; set; }
        public Nullable<double> COD_HC_V { get; set; }
        public Nullable<double> COD_HM_V { get; set; }
        public Nullable<double> MAB_V { get; set; }
        public string NOE_PAR { get; set; }
        public Nullable<double> MAB_PAR { get; set; }
        public Nullable<double> MAB_PAR_N { get; set; }
        public Nullable<double> MAB_PAR_C { get; set; }
        public Nullable<double> COD_FPA { get; set; }
        public string TAVASOT { get; set; }
        public Nullable<double> AA_MAB { get; set; }
        public Nullable<double> cod_hc_g { get; set; }
        public Nullable<double> cod_hm_g { get; set; }
        public Nullable<double> mab_g { get; set; }
        public Nullable<double> cod_hc_f { get; set; }
        public Nullable<double> cod_hm_f { get; set; }
        public Nullable<double> mab_f { get; set; }
        public string adder { get; set; }
        public string editor { get; set; }
        public Nullable<int> editCount { get; set; }
        public Nullable<double> cod_hc_vas { get; set; }
        public Nullable<double> cod_hm_vas { get; set; }
        public Nullable<bool> Do_aa { get; set; }
        public Nullable<double> COD_HM_N { get; set; }
        public string cod_Eshterak { get; set; }
        public Nullable<double> takh2 { get; set; }
        public string tozih2 { get; set; }
        public Nullable<double> cod_hc_tas { get; set; }
        public Nullable<double> cod_hm_tas { get; set; }
        public Nullable<double> mab_tas { get; set; }
        public string ref_v { get; set; }
        public string ref_f { get; set; }
        public string ref_haz { get; set; }
        public string ref_tas { get; set; }
        public Nullable<double> area { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public string CrateDate { get; set; }
        public string UpdateDate { get; set; }
    }
}
