//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEditor.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class karbar
    {
        public int SHS_ID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string pas { get; set; }
        public Nullable<bool> tsCRM_Customer { get; set; }
        public Nullable<bool> BaddCRM_Customer { get; set; }
        public Nullable<bool> BeditCRM_Customer { get; set; }
        public Nullable<bool> BdelCRM_Customer { get; set; }
        public Nullable<bool> tsrepCRM_Customer { get; set; }
        public Nullable<bool> tsCRM_Company { get; set; }
        public Nullable<bool> baddCRM_Company { get; set; }
        public Nullable<bool> beditCRM_Company { get; set; }
        public Nullable<bool> bdelCRM_Company { get; set; }
        public Nullable<bool> tsrepCRM_Company { get; set; }
        public Nullable<bool> tsCRM_Agreement { get; set; }
        public Nullable<bool> baddCRM_Agreement { get; set; }
        public Nullable<bool> beditCRM_Agreement { get; set; }
        public Nullable<bool> bdelCRM_Agreement { get; set; }
        public Nullable<bool> tsrepCRM_Agreement { get; set; }
        public Nullable<bool> tsCRM_Discount { get; set; }
        public Nullable<bool> baddCRM_Discount { get; set; }
        public Nullable<bool> beditCRM_Discount { get; set; }
        public Nullable<bool> bdelCRM_Discount { get; set; }
        public Nullable<bool> tsrepCRM_Discount { get; set; }
        public Nullable<bool> bdelCRM_log { get; set; }
        public Nullable<bool> tsrepCRM_log { get; set; }
        public Nullable<bool> tsCRM_Setting { get; set; }
        public Nullable<bool> beditCRM_Setting { get; set; }
        public Nullable<bool> tsCRM_SMSSender { get; set; }
        public Nullable<bool> baddCRM_SMSSender { get; set; }
        public Nullable<bool> beditCRM_SMSSender { get; set; }
        public Nullable<bool> bdelCRM_SMSSender { get; set; }
        public Nullable<bool> tskarbar { get; set; }
        public Nullable<bool> Admin { get; set; }
    
        public virtual SalMaly SalMaly { get; set; }
    }
}
