//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEditor.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Product
    {
        public int Id_Year { get; set; }
        public double id { get; set; }
        public string NAME { get; set; }
        public Nullable<double> id_store { get; set; }
        public string name_store { get; set; }
        public Nullable<double> BuyPrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string UintName { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
