//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEditor.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_SaleList
    {
        public int Id_Year { get; set; }
        public double id_Sale { get; set; }
        public double NO { get; set; }
        public Nullable<double> id_Product { get; set; }
        public Nullable<double> id_Store { get; set; }
        public string Name_Store { get; set; }
        public string Name { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> pay { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> amount2 { get; set; }
        public Nullable<double> id_book { get; set; }
        public Nullable<double> id_account { get; set; }
        public string SaleDate { get; set; }
        public string SaleTime { get; set; }
    }
}
